language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*

matrix:
    fast_finish: true

before_install:
    - echo "memory_limit=520M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer self-update

before_script:
  - export BUILD_HOME=`pwd`
  - wget https://phar.phpunit.de/phpunit.phar
  - mv phpunit.phar phpunit
  - chmod +x phpunit
  - mv $(which phpunit) phpunit

install:
#  - ./phpunit_setup.sh
  - composer install
  - php Tests/Functional/console doctrine:database:create --env=test
  - php Tests/Functional/console doctrine:schema:create --env=test
  # - php Tests/Functional/console doctrine:fixtures:load -n --env=test

script: phpunit --coverage-text

services:
  - mysql

