language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - php: 5.6
          env: SYMFONY_VERSION=3.0.*
        - php: 7.0
          env: SYMFONY_VERSION=3.0.*

before_install:
    - echo "memory_limit=520M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer self-update

install:
  - composer install
  - php Tests/Functional/console doctrine:database:create --env=test
  - php Tests/Functional/console doctrine:schema:create --env=test
  # - php Tests/Functional/console doctrine:fixtures:load -n --env=test

script: phpunit --coverage-text

services:
  - mysql

