<?php

namespace Alpixel\Bundle\ShopBundle\Repository;

/**
 * CartRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends AbstractCartRepository
{
}
