<?php

namespace Alpixel\Bundle\ShopBundle\Repository;

use Alpixel\Bundle\ShopBundle\Entity\Customer;

/**
 * CartRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryCurrentCartByCustomer(Customer $customer)
    {
        return $this->createQueryBuilder('c')
            ->where('c.customer = :customer')
            ->andWhere('c.order IS NULL')
            ->setParameter('customer', $customer)
            ->orderBy('c.createdAt', 'DESC')
            ->setMaxResults(1);
    }

    public function findOneCurrentCartByCustomer(Customer $customer)
    {
        return $this->queryCurrentCartByCustomer($customer)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
