<?php

namespace Alpixel\Bundle\ShopBundle\Repository;

use Alpixel\Bundle\ShopBundle\Entity\Customer;

/**
 * CartRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSavedCarts(Customer $customer)
    {
        return $this->createQueryBuilder('c')
            ->addSelect('o')
            ->leftJoin('c.order', 'o')
            ->leftJoin('c.customer', 'customer')
            ->where('c.customer = :customer')
            ->andWhere('o.id IS NULL')
            ->andWhere('customer.currentCart != c.id')
            ->setParameter('customer', $customer)
            ->orderBy('c.createdAt', 'DESC')
            ->groupBy('c.id')
            ->getQuery()
            ->getResult();
    }
}
