<?php

namespace Alpixel\Bundle\ShopBundle\Repository;

/**
 * DescriptionTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescriptionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
