<?php

namespace Alpixel\Bundle\ShopBundle\Repository;

/**
 * ProductDescriptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
